apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-bootstrap
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: talos-test-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: talos-test-root-ca
  secretName: talos-test-root-ca-secret
  duration: 8760h   # 1 Jahr
  renewBefore: 720h  # 30 Tage vor Ablauf
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-bootstrap
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: talos-test-ca
spec:
  ca:
    secretName: talos-test-root-ca-secret
