apiVersion: v1
kind: ConfigMap
metadata:
    name: test-config
    namespace: default
data:
    config.yaml: |
        key1: value1
        key2: value2
    app.properties: |
        setting1=value1
        setting2=value2